backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

site_url: https://electricite-eljp.com/
display_url: https://electricite-eljp.com/
logo_url: https://electricite-eljp.com/images/eljp-logo-desktop.png
locale: 'fr'

media_folder: themes/hugo-hero-theme-master/assets/img
public_folder: /img
collections:
  - name: 'sectionprestations'
    label: 'Section Prestations'
    description: 'Modifiez ici la page principale nommée Prestations'
    folder: 'content/french/prestations'
    create: false
    editor:
      preview: true
    filter: {field: "mainsection", value: "true"}
    fields:
      - { label: 'Titre SEO', name: 'title', widget: 'string', hint: 'Ceci est le Titre SEO qui apparait depuis Google lors dune recherche mais napparait nulle part sur votre site' }
      - { label: 'Description SEO', name: 'description', widget: 'string', hint: 'Ceci est la Description SEO qui apparait depuis Google lors dune recherche + pensez à y introduire vos mots-clés + napparaitra nulle part sur votre site' }
      - { label: 'Contenu', name: 'body', widget: 'markdown', hint: 'Contenu de la page + brêve introduction qui apparait juste au dessus de la liste de vos prestations' }
  - name: 'mesprestations'
    label: 'Mes Prestations'
    description: 'Modifiez ici la page dédiée à chacune de vos prestations'
    folder: 'content/french/prestations'
    create: true
    editor:
      preview: true
    filter: {field: "mainsection", value: "false"}
    fields:
      - { label: 'Intitulé sous-section et Titre SEO', name: 'title', widget: 'string', hint: 'Ceci est lintitulé de votre prestation sur le site + le titre SEO de votre page' }
      - { label: 'Description SEO', name: 'description', widget: 'string', hint: 'Ceci est la Description SEO qui apparaitra depuis Google lors dune recherche + pensez à y introduire vos mots-clés + napparaitra nulle part sur votre site' }
      - { label: 'Contenu', name: 'body', widget: 'markdown', hint: 'Contenu de la page + parlez de votre prestation en détail + ajoutez une ou deux photos si nécessaire + soyez concis mais percutant + pensez à introduire vos mots clés' }

  - name: 'sectionquisuisje'
    label: 'Section Qui suis-je'
    description: 'Modifiez ici la page principale nommée Qui suis-je'
    folder: 'content/french/quisuisje'
    create: false
    editor:
      preview: true
    filter: {field: "mainsection", value: "true"}
    fields:
      - { label: 'Titre SEO', name: 'title', widget: 'string', hint: 'Ceci est le Titre SEO qui apparait depuis Google lors dune recherche mais napparait nulle part sur votre site' }
      - { label: 'Description SEO', name: 'description', widget: 'string', hint: 'Ceci est la Description SEO qui apparait depuis Google lors dune recherche + pensez à y introduire vos mots-clés + napparaitra nulle part sur votre site' }
      - { label: 'Contenu', name: 'body', widget: 'markdown', hint: 'Contenu de la page + ajoutez quelques mots clés si possible' }

  - name: 'contact'
    label: 'Contact'
    description: 'Modifiez ici votre page Contact'
    folder: 'content/french/contact'
    create: false
    editor:
      preview: true
    fields:
      - { label: 'Titre SEO', name: 'title', widget: 'string', hint: 'Ceci est le Titre SEO qui apparait depuis Google lors dune recherche mais napparait nulle part sur votre site' }
      - { label: 'Description SEO', name: 'description', widget: 'string', hint: 'Ceci est la Description SEO qui apparait depuis Google lors dune recherche + pensez à y introduire vos mots-clés + napparaitra nulle part sur votre site' }

  - name: 'mentionslegales'
    label: 'Mentions légales'
    description: 'Modifiez ici vos Mentions Légales'
    folder: 'content/french/mentionslegales'
    create: false
    editor:
      preview: true
    fields:
      - { label: 'Titre SEO', name: 'title', widget: 'string', hint: 'Ceci est le Titre SEO qui apparait depuis Google lors dune recherche mais napparait nulle part sur votre site' }
      - { label: 'Description SEO', name: 'description', widget: 'string', hint: 'Ceci est la Description SEO qui apparait depuis Google lors dune recherche + pensez à y introduire vos mots-clés + napparaitra nulle part sur votre site' }
      - { label: 'Contenu', name: 'body', widget: 'markdown', hint: 'Contenu de la page + listez ici vos Mentions Légales' }
